image: python:3.7.3

pipelines:
  default:
    - step:
        caches:
          - pip
        script: # Modify the commands below to build your repository.
          - free -h
          - free -g
          - pip install scipy
          - pip install tensorflow==2.0.0
          - python test.py
          #- pip install -r requirements.txt
